name: GitHub Actions Demo
run-name: "${{ github.actor }} is testing out GitHub Actions 🚀"

'on':
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  setup-java:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up JDK 17 with Zulu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

  grant-permission:
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

  build:
    runs-on: ubuntu-latest
    needs: grant-permission
    steps:
      - name: Build with Gradle
        run: ./gradlew build

  build-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Release AAB
        run: ./gradlew bundleRelease

  sign-aab:
    runs-on: ubuntu-latest
    needs: build-release
    permissions: write-all
    steps:
      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'

  upload-aab:
    runs-on: ubuntu-latest
    needs: sign-aab
    permissions: write-all
    steps:
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.aab

  create-release:
    runs-on: ubuntu-latest
    needs: upload-aab
    permissions: write-all
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.0'
          release_name: 'v1.0.0'
          body: "First release of the app"
          draft: false
          prerelease: false

  upload-release-asset:
    runs-on: ubuntu-latest
    needs: create-release
    permissions: write-all
    steps:
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/octet-stream

  send-mail:
    runs-on: ubuntu-latest
    needs: upload-release-asset
    permissions: write-all
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: New Bugit APP release built
          to: Salahsamy512@gmail.com
          from: GitHub Action
          body: "A new release has been created. Please find the attached app-release.aab file."
          secure: true
          ignore_cert: true
          priority: low
          attachments: app/build/outputs/bundle/release/app-release.aab
